In [1]:
import numpy as np

In [11]:
a = np.arange(12).reshape(2,3,2)

In [12]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [15]:
np.linspace(5, 12, 8)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [17]:
a = np.arange(1, 17).reshape(4,4)

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
a[1::2,1::2]

array([[ 6,  8],
       [14, 16]])

In [21]:
a[[1, 2], [1, 2]]

array([ 6, 11])

In [26]:
a[[1,2], :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a[:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [28]:
a[[1,2], [1,2]]

array([ 6, 11])

In [30]:
b = np.arange(10)

In [31]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b.dtype

dtype('int64')

In [33]:
b.shape

(10,)

In [34]:
b.ndim

1

In [38]:
c = b.reshape(1,10)

In [39]:
c

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
c.shape

(1, 10)

In [41]:
b.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [42]:
b.reshape(10,1).shape

(10, 1)

In [43]:
b.dtype

dtype('int64')

In [44]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.array([1,2,3,0], dtype='bool')

array([ True,  True,  True, False])

In [58]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [59]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
arr[1, 2]

8

In [61]:
arr = np.array([1,2,3,4,5,6,7])

In [62]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
arr[2:5]

array([3, 4, 5])

In [64]:
arr.shape

(7,)

In [65]:
arr = np.array([1,2,3,4,5,6,7])

In [66]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
arr[::2]

array([1, 3, 5, 7])

In [ ]:
b